version: "3"

services:
  web-node:
    image: node:12.18-alpine
    container_name: contactme-web-node
    command: sh ./docker/web-node/command.sh
    working_dir: /home/contactme
    volumes:
      - .:/home/contactme

  web-php:
    build: .
    container_name: contactme-web-php
    command: sh ./docker/web-php/command.sh
    working_dir: /home/contactme
    ports:
      - 8085:80
    volumes:
      - .:/home/contactme
    depends_on:
      - mailhog
      - database
    links:
      - mailhog
      - database

  mailhog:
    image: mailhog/mailhog
    container_name: contactme-mailhog
    ports:
      - 1025:1025
      - 8025:8025

  database:
    image: mysql:8
    container_name: contactme-database
    ports:
      - 3309:3306
    environment:
      - MYSQL_DATABASE=contactme
      - MYSQL_ROOT_PASSWORD=root
